### ISSUE TITLE
Make it possible to save all the data related to a game

### ISSUE THREAD

**Issue by gcoter** [gcoter/magic-the-gathering-python#25]
When running a game, we could create a folder `run-{uuid}/` and for each action write a JSON file `action-{i}.json` with a structure like this:
```
{
    "game_state": {The full `GameState` *before* the action is executed},
    "action": {The `Action` being executed}
}
```

At the end of the game, one final JSON file `results.json` could record the results of the game, something like:
```
{
    "winner_player_index": 1,
    ...
}
```

**Comment by MaximeBastion** [comment]
If writing takes time, I assume that we also want a flag to disable this, in the scenario where we want to run many games as efficiently as possible?

**Comment by gcoter** [comment]
Yes you are right, by default we could disable writing :slightly_smiling_face:
